### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [afshaan4/loudsounds#1]
Hi @afshaan4  I am a graphic artist and I would like to design a logo for your project for free. I am improving my portfolio and I want to contribute at the same time. :)  If you are interested and will allow me, I will begin asap. Thanks! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by skittlemittle** [comment]
Sorry but I don't think I need a logo for this, its just a small script I made for fun.
