### ISSUE TITLE
crashes after 2min45seconds on pi1B

### ISSUE THREAD

**Issue by skittlemittle** [afshaan4/loudsounds#2]
running it on a pi and after 2min25seconds it just starts recording even though there is no sound above the threshold, could be an int overflow?

solution for now: have a cron job that just restarts it every 2 minutes with the same args.

**Comment by skittlemittle** [comment]
could be the thing increasing the sensitivity of the mic

**Comment by skittlemittle** [comment]
nope it aint that, testing on my laptop it works just fine, hmmmmmmmmmmmmm

**Comment by skittlemittle** [comment]
so it did start acting weird on my laptop after long silent periods because:

```python
# if it's too quiet for too long
            if self.quietcount > UNDERSENSITIVE:
                # set threshold back to original
                self.tap_threshold *= 0.9
```

this bit just gradually lowered the threshold every two minutes, i did fix it for my machine by doing:

```python3
# if it's too quiet for too long
            if self.quietcount > UNDERSENSITIVE:
                # set threshold back to original
                self.tap_threshold = args.sensitivity
```

well see about the pi

**Comment by afshaan4** [comment]
so it did start acting weird on my laptop after long "silent periods" because:

```python
# if it's too quiet for too long
            if self.quietcount > UNDERSENSITIVE:
                # set threshold back to original
                self.tap_threshold *= 0.9
```

this bit just gradually lowered the threshold every two minutes, I did fix it for my machine by doing:

```python3
# if it's too quiet for too long
            if self.quietcount > UNDERSENSITIVE:
                # set threshold back to original
                self.tap_threshold = args.sensitivity
```

well see about the pi
